version: 2.1
workflows:
  test-build-app:
    jobs:
      - test-app
      - build-app:
          requires:
            - test-app

orbs:
  node: circleci/node@5.0.2
jobs:
  test-app:
    working_directory: ~/repo
    docker:
      - image: circleci/node:16.10.0

    ## setup
    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      ## run tests
      - run:
          name: jest tests
          command: yarn test
  
  build-app:
    working_directory: ~/repo
    docker:
      - image: circleci/node:16.10.0

    ## setup
    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      # Build App
      - run:
          name: Build React App
          command: npm run build

      - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            - ./dist
      - run:
          name: Deploy to Netlify
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=dist

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main