version: 2.1
orbs:
  node: circleci/node@7.2.0
jobs:
  test-app:
    working_directory: ~/repo
    docker:
      - image: circleci/node:17.2.0

    ## setup
    steps:
      - checkout

      - restore_cache:
          keys: 
            - node-v1-{{ checksum "package.json" }}-{{ arch }}
            - node-v1-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      ## run tests
      - run:
          name: jest tests
          command: yarn test
  
  build-and-deploy-app:
    working_directory: ~/repo
    docker:
      - image: circleci/node:16.10.0

    ## setup
    steps:
      - checkout
      
      - restore_cache:
          keys: 
            - node-v1-{{ checksum "package.json" }}-{{ arch }}
            - node-v1-
      # Build App
      - run:
          name: Build React App
          command: yarn build:prod

      - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            - ./dist
      - run:
          name: Deploy to Netlify
          # ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=dist
          command: yarn netlify:deploy

workflows:
  version: 2
  test-build-deploy-app:
    jobs:
      - test-app
      - build-and-deploy-app:
          requires:
            - test-app
          filters:
            branches:
              only:
                - main
